"""empty message

Revision ID: 29e66275737b
Revises: 644487eac876
Create Date: 2020-04-03 22:03:31.092294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e66275737b'
down_revision = '644487eac876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wiki', sa.Column('summary', sa.String(length=255), nullable=True))
    op.add_column('wiki', sa.Column('template', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wiki', 'template')
    op.drop_column('wiki', 'summary')
    # ### end Alembic commands ###
