"""empty message

Revision ID: b174cf2bbbd6
Revises: 29e66275737b
Create Date: 2020-04-05 20:03:31.998498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b174cf2bbbd6'
down_revision = '29e66275737b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'suggested_article', ['page_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suggested_article', type_='unique')
    # ### end Alembic commands ###
