"""empty message

Revision ID: c3450f34caa5
Revises: 6586de0b2c1a
Create Date: 2020-04-15 19:31:55.728481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3450f34caa5'
down_revision = '6586de0b2c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggested_article', sa.Column('dismissed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggested_article', 'dismissed')
    # ### end Alembic commands ###
