"""empty message

Revision ID: c4ccac140986
Revises: ccee79dfd336
Create Date: 2020-04-03 20:06:11.533902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ccac140986'
down_revision = 'ccee79dfd336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggested_article', sa.Column('bytes_per_link', sa.Integer(), nullable=True))
    op.add_column('suggested_article', sa.Column('page_id', sa.Integer(), nullable=True))
    op.add_column('suggested_article', sa.Column('probability', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggested_article', 'probability')
    op.drop_column('suggested_article', 'page_id')
    op.drop_column('suggested_article', 'bytes_per_link')
    # ### end Alembic commands ###
