"""empty message

Revision ID: fe1fb94c885d
Revises: 
Create Date: 2020-04-03 12:07:05.484645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1fb94c885d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wiki',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dbname', sa.String(length=255), nullable=True),
    sa.Column('featured_articles_category', sa.String(length=255), nullable=True),
    sa.Column('bytes_per_link_avg', sa.Integer(), nullable=True),
    sa.Column('bytes_per_link_max', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggested_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wiki_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wiki_id'], ['wiki.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggested_article')
    op.drop_table('wiki')
    op.drop_table('user')
    # ### end Alembic commands ###
